In [2]:
import pandas as pd
import openpyxl

In [5]:
path: r"H:\MATÉRIAS TECNICAS\TERCEIRA ETAPA\PYTHON\Atividade3\Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"

In [13]:
superior = pd.DataFrame({
    "Região": ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"],
    "Homens": [590558, 1744994, 5391638, 1768855, 982489],
    "Mulheres": [934609, 3003939, 7437191, 2570005, 1430013]
})

superior

superior.to_excel("01_superior_por_regiao.xlsx", index=False)

In [14]:
ctem = pd.DataFrame({
    "Região": ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"],
    "Homens": [133055, 389993, 1588874, 427372, 211124],
    "Mulheres": [76601, 231395, 739247, 235543, 115834]
})

ctem

ctem.to_excel("02_ctem_por_regiao.xlsx", index=False)

In [15]:
educacao_saude = pd.DataFrame({
    "Região": ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"],
    "Homens": [141169, 363905, 768288, 248574, 156048],
    "Mulheres": [458616, 1458181, 2884108, 1007718, 593101]
})

educacao_saude

educacao_saude.to_excel(
    "03_educacao_servicos_saude_bem_estar.xlsx",
    index=False
)

In [11]:
print("Tabela 1 - Curso Superior")
display(superior)

print("Tabela 2 - CTEM")
display(ctem)

print("Tabela 3 - Educação, Serviços pessoais, Saúde e Bem-estar")
display(educacao_saude)

Tabela 1 - Curso Superior

         Região   Homens  Mulheres
0         Norte   590558    934609
1      Nordeste  1744994   3003939
2       Sudeste  5391638   7437191
3           Sul  1768855   2570005
4  Centro-Oeste   982489   1430013

Tabela 2 - CTEM

         Região   Homens  Mulheres
0         Norte   133055     76601
1      Nordeste   389993    231395
2       Sudeste  1588874    739247
3           Sul   427372    235543
4  Centro-Oeste   211124    115834

Tabela 3 - Educação, Serviços pessoais, Saúde e Bem-estar

         Região  Homens  Mulheres
0         Norte  141169    458616
1      Nordeste  363905   1458181
2       Sudeste  768288   2884108
3           Sul  248574   1007718
4  Centro-Oeste  156048    593101